name: gcc
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  gcc-latest:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure
        working-directory: src/
        run: mkdir build && cd build && cmake ..
      - name: build
        working-directory: src/
        run: cmake --build build